name: Build Docker Image
on:
  create:
    tags:
      - '*'
  workflow_dispatch:    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v1
        with: 
          context: ./super_calculator
          file: ./super_calculator/Dockerfile
          push: true
          tags: emmanuelntankeu/projet4dvp
          
          
